version: "3"

services:
  s3-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8090:8080"

  minio:
    image: minio/minio:RELEASE.2024-03-30T09-41-56Z.fips
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.minio
    command: server /data --console-address ":9001"


volumes:
  minio_data: